{% set name = "checkov" %}
{% set version = "3.2.244" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/checkov-{{ version }}.tar.gz
  sha256: 72af9b6571823dd1b5ca1da782b818f09ddc64a40a514340eeea90672e0dd5e3

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<39 or (py<311 and osx and x86_64) or py>311]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pyyaml
    - pip
  run:
    - python
    - bc-python-hcl2 ==0.4.2
    - bc-detect-secrets ==1.5.15
    - bc-jsonpath-ng ==1.6.1
    - pycep-parser ==0.4.1
    - tabulate >=0.9.0,<0.10.0
    - colorama >=0.4.3,<0.5.0
    - termcolor >=1.1.0,<2.4.0
    - junit-xml >=1.9,<2.0
    - dpath ==2.1.3
    - pyyaml >=6.0.0,<7.0.0
    - boto3 ==1.34.25
    - botocore ==1.34.25
    - gitpython >=3.1.30,<4.0.0
    - jmespath >=1.0.0,<2.0.0
    - tqdm >=4.65.0,<5.0.0
    - packaging >=23.0,<24.0
    - cloudsplaining >=0.6.2,<0.7.0
    - networkx <2.7
    - dockerfile-parse >=2.0.0,<3.0.0
    - docker-py >=6.0.1,<8.0.0
    - configargparse >=1.5.3,<2.0.0
    - argcomplete >=3.0.0,<4.0.0
    - typing-extensions >=4.5.0,<5.0.0
    - importlib-metadata >=6.0.0,<8.0.0
    - cachetools >=5.2.0,<6.0.0
    - cyclonedx-python-lib >=6.0.0,<7.0.0
    - packageurl-python >=0.11.1,<0.14.0
    - click >=8.1.0,<9.0.0
    - aiohttp >=3.8.0,<4.0.0
    - aiodns >=3.0.0,<4.0.0
    - aiomultiprocess >=0.9.0,<0.10.0
    - schema <=0.7.5
    - jsonschema >=4.17.0,<5.0.0
    - prettytable >=3.6.0,<4.0.0
    - charset-normalizer >=3.1.0,<4.0.0
    - pyston_lite_autoload ==2.3.5  # [py<311 and unix and x86_64]
    - pyston_lite ==2.3.5  # [py<311 and unix and x86_64]
    - requests >=2.28.0,<3.0.0
    - yarl >=1.9.1,<2.0.0
    - openai <1.0.0
    - spdx-tools >=0.8.0,<0.9.0
    - license-expression >=30.1.0,<31.0.0
    - rustworkx >=0.13.0,<0.14.0
    - pydantic >=2.0.0,<3.0.0
    - urllib3 >=1.26.0,<2.0.0

test:
  imports:
    - checkov
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bridgecrewio/checkov
  summary: Infrastructure as code static analysis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
