{% set name = "checkov" %}
{% set version = "3.0.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/checkov-{{ version }}.tar.gz
  sha256: 8691d27928ae5ab238ad24f6b69363e6d32a04b9aba0be4500d46c0fb9052be2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<39 or (py<311 and osx and x86_64)]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pyyaml
    - pip
  run:
    - python
    - bc-python-hcl2 ==0.3.51
    - bc-detect-secrets ==1.4.30
    - bc-jsonpath-ng ==1.5.9
    - tabulate
    - colorama
    - termcolor
    - junit-xml >=1.9
    - dpath ==2.1.3
    - pyyaml >=5.4.1
    - boto3 >=1.17
    - gitpython
    - jmespath
    - tqdm
    - update_checker
    - semantic_version
    - packaging
    - cloudsplaining >=0.4.3
    - networkx <2.7
    - python-igraph <0.11.0
    - dockerfile-parse
    - docker-py
    - configargparse
    - argcomplete
    - typing-extensions >=4.1.0
    - importlib-metadata >=0.12
    - cachetools
    - cyclonedx-python-lib >=5.0.0
    - packageurl-python
    - click >=8.0.0
    - aiohttp
    - aiodns
    - aiomultiprocess
    - jsonschema <5.0.0,>=4.6.0
    - prettytable >=3.0.0
    - pycep-parser ==0.4.1
    - charset-normalizer
    - pyston_lite_autoload ==2.3.5  # [py<311 and unix and x86_64]
    - pyston_lite ==2.3.5  # [py<311 and unix and x86_64]
    - schema
    - requests >=2.27.0
    - yarl
    - openai
    - spdx-tools >=0.8.0,<0.9.0
    - license-expression
    - rustworkx
    - pydantic

test:
  imports:
    - checkov
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bridgecrewio/checkov
  summary: Infrastructure as code static analysis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
