schema_version: 1

context:
  name: checkov
  version: 3.2.443

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/checkov-${{ version }}.tar.gz
  sha256: 42609d90d5ac710deead0477964605a5837c58ac8587ec4b286263190421e4ff

build:
  number: 0
  skip: (match(python, "<3.11") and osx and x86_64) or match(python, ">3.11")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
  host:
    - python
    - pyyaml
    - pip
    - setuptools
  run:
    - urllib3 ==1.26.20
    - typing_extensions <5.0.0,>=4.5.0
    - python
    - bc-python-hcl2 ==0.4.2
    - bc-detect-secrets ==1.5.44
    - bc-jsonpath-ng ==1.6.1
    - pycep-parser ==0.5.1
    - tabulate >=0.9.0,<0.10.0
    - colorama >=0.4.3,<0.5.0
    - termcolor >=1.1.0,<2.4.0
    - junit-xml >=1.9,<2.0
    - dpath ==2.1.3
    - pyyaml <7.0.0,>=6.0.0
    - boto3 ==1.35.49
    - botocore ==1.35.49
    - gitpython >=3.1.30,<4.0.0
    - jmespath >=1.0.0,<2.0.0
    - tqdm <5.0.0,>=4.65.0
    - packaging >=23.0,<24.0
    - cloudsplaining <0.8.0,>=0.7.0
    - networkx <2.7
    - dockerfile-parse <3.0.0,>=2.0.0
    - docker-py >=6.0.1,<8.0.0
    - configargparse >=1.5.3,<2.0.0
    - argcomplete <4.0.0,>=3.0.0
    - typing-extensions >=4.5.0,<5.0.0
    - importlib-metadata >=6.0.0,<8.0.0
    - cachetools >=5.2.0,<6.0.0
    - cyclonedx-python-lib <8.0.0,>=6.0.0
    - packageurl-python <0.14.0,>=0.11.1
    - click <9.0.0,>=8.1.0
    - aiohttp <4.0.0,>=3.8.0
    - aiodns <4.0.0,>=3.0.0
    - aiomultiprocess >=0.9.0,<0.10.0
    - schema <=0.7.5
    - jsonschema <5.0.0,>=4.17.0
    - prettytable <4.0.0,>=3.6.0
    - charset-normalizer <4.0.0,>=3.1.0
    - if: match(python, "<3.11") and unix and x86_64
      then: pyston_lite_autoload ==2.3.5
    - if: match(python, "<3.11") and unix and x86_64
      then: pyston_lite ==2.3.5
    - requests <3.0.0,>=2.28.0
    - yarl <2.0.0,>=1.9.1
    - openai <1.0.0
    - spdx-tools >=0.8.0,<0.9.0
    - license-expression <31.0.0,>=30.1.0
    - rustworkx >=0.13.0,<1.0.0
    - pydantic <3.0.0,>=2.0.0
    - asteval ==1.0.5

tests:
  - python:
      imports:
        - checkov

about:
  summary: Infrastructure as code static analysis
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/bridgecrewio/checkov

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
    - xhochy
