github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
bot:
  automerge: true
  inspection: update-grayskull
test: native_and_emulated
conda_build_tool: rattler-build
conda_install_tool: pixi
